AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  ProcessPayRespalarm:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Description: ''
      MemorySize: 160
      Timeout: 3
      Role: >-
        arn:aws:iam::578915239930:role/service-role/ProcessPayResp_alarm-role-vy02op6a
      Environment:
        Variables:
          ERROR_DASHBOARD: >-
            https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2#dashboards:name=payment-serviceV2
          SLACK_WEBHOOK_URL: >-
            https://hooks.slack.com/services/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 
      RuntimePolicy:
        UpdateRuntimeOn: Auto
